### ISSUE TITLE
Why logster is restricted to only development or production environment?

### ISSUE THREAD

**Issue by jiajiawang** [discourse/logster#26]
I can see that currently logster is restricted to only development or production environment.
https://github.com/discourse/logster/blob/master/lib/logster/rails/railtie.rb#L8

Is there any particular reasons for this?

Because I'd like to use logster in other environments like staging as well.

**Comment by SamSaffron** [comment]
I mainly wanted to ensure it does not run in test, there is special logic
for production.

Perhaps clean that up so there is a special init method and call it from
staging by hand ?

**Comment by jiajiawang** [comment]
#27 
Made a pull request for this issue.
Please review it.

**Comment by jiajiawang** [comment]
Closed as pull request has been merged.
