### ISSUE TITLE
logster only works on /logs path

### ISSUE THREAD

**Issue by resure** [discourse/logster#29]
Usage of other paths (like `mount Logster::Web => "/_logs"`) lead to the plain `not found` response.

**Comment by SamSaffron** [comment]
pretty sure we got this working elsewhere.

**Comment by dcalixto** [comment]
so have no way to change the path?

**Comment by gauravtiwari** [comment]
Just to update, this can be changed using the `subdirectory` option:

```rb
Logster.config.subdirectory = "/secret/logs"
```

@SamSaffron Perhaps, this issue can be closed?

**Comment by SamSaffron** [comment]
Thanks @gauravtiwari  !
