### ISSUE TITLE
Doesn't work in production

### ISSUE THREAD

**Issue by n-rodriguez** [discourse/logster#34]
Hi! Logster works in development but not on my production server.

The page is well displayed, Ajax call are made to refresh the view, but nothing appears...

Any idea?

**Comment by SamSaffron** [comment]
it works :) 

you just need to mount the viewer 

See: 

https://github.com/discourse/discourse/blob/master/config/routes.rb#L18-L24

and 

https://github.com/discourse/discourse/blob/master/config/initializers/logster.rb

Would you mind doing a PR for documentation after you get it going ?

**Comment by n-rodriguez** [comment]
Thanks for your answer. That's what I've done : https://github.com/jbox-web/deploy-it/blob/master/config/routes.rb#L24. Maybe should I try with an other constraint?

**Comment by SamSaffron** [comment]
Keep in mind in prd we default to warning and up. Open a rails console and
log an error, you should see it.

**Comment by n-rodriguez** [comment]
It works! Sorry for the noise. Very good gem :+1: 

By the way, can I use logster to monitor an other log file / logger?

**Comment by SamSaffron** [comment]
Sure, you can chain it to whatever, have a look at the test suite it should
clarify a lot of the apis.

**Comment by bitsapien** [comment]
My log level in `production.rb` is set to `:info`, but I still see that my screen is blank. Only logs with level set to `fatal` show up. It works fine in development though.

**Comment by yhmiao** [comment]
@bitsapien Have you worked out why it is showing in development but not production? I'm having the same issue and can't seem to figure out why.

**Comment by bitsapien** [comment]
@yhmiao It works fine for me now. Check your logs dump on production to check whether you are getting any logs at all.

**Comment by yhmiao** [comment]
@bitsapien The config.log_level is set to :debug in production.rb. Production.log does show all messages from all levels. But in '/logs' it only shows :warn, :error, and :fatal. Is this normal?

**Comment by nahankid** [comment]
Hi, I used Logster back in 2017 and loved it. Using it again and it's working in dev but not prod or staging. While trying to troubleshoot it, I noticed two things:

1. In the server logs I see that Logster is looking at different IPs. Is that normal? 

Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.71.159.45 at 2024-04-18 04:52:18 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.71.159.46 at 2024-04-18 04:52:30 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.71.159.45 at 2024-04-18 04:52:36 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.71.154.236 at 2024-04-18 04:53:15 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.71.154.194 at 2024-04-18 04:53:54 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 172.69.135.149 at 2024-04-18 04:54:33 +0000
Started GET "/logs/messages.json?filter=0_1_2_3_4_5" for 162.158.166.226 at 2024-04-18 04:55:12 +0000

2. In dev, redis has many "logster-env-*" keys but none in staging.

What am I doing wrong?

Btw, the rails version is 4.2.9 (same app from 2017)

Thanks in advance!

**Comment by zealot128** [comment]
I was also puzzled after seeing no events on production. Only errors/warnings came after a while.

Then I discovered that Logster really does ignore info+debug calls: https://github.com/discourse/logster/blob/25375250fb8a5c312e9c55a75f6048637aad2c69/lib/logster/rails/railtie.rb#L16

It seems to be disabled for a reason, but if you want to see info logs in prod, too, then you can change it in an initializer:

```
Logster.logger.store.level = 1
```

But then you will get the whole beauty of the Rails default logger with useless junk like "rendered in 0.2ms" with each line unrelated to the request etc. There might be more work needed to combine those. 
Maybe using stuff like Lograge will help here, by combining everything in one line. 
I also used tagged logging with request_id, but that had no effect on Logster, only on the standard production.log
