### ISSUE TITLE
Unable to set environments in application.rb

### ISSUE THREAD

**Issue by aaronbronow** [discourse/logster#37]
I've got logster to work in development and productions modes. Now I'm trying to get it to work in staging.

When I try set environments `Logster.set_environments([:development, :staging, :production])` in application.rb I get this error on startup:

ERROR -- : undefined method `environments=' for nil:NilClass (NoMethodError)
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/logster-1.0.1/lib/logster.rb:45:in`set_environments'

I am able to set store in application.rb though.

**Comment by bitsapien** [comment]
+1

**Comment by bitsapien** [comment]
Adding this line ->
```
Logster.config 
```
before `Logster.set_environments([:development, :staging, :production])` does the job.

This is a workaround to the problem. I would like to know what the solution should be.
