### ISSUE TITLE
Unable to use Logster with https://github.com/lulalala/multi_logger

### ISSUE THREAD

**Issue by dmitrypol** [discourse/logster#42]
I love Logster functionality but I can't use it with MultiLogger.  I configured MultiLogger gem like this:

```
# config/initializers/multie_logger.rb
MultiLogger.add_logger('mylog')
```

But now I get these:  
undefined method `mylog' for #Logster::Logger:0x00000009c11ae8

I tried this config `Rails.logger.extend(ActiveSupport::Logger.broadcast(Logster.logger))` but no luck.  

I am using Rails 4.1.14.2.  Apologies if this is a really silly question but does anyone have suggestions?

**Comment by SamSaffron** [comment]
no idea how this multilogger gem works, but logster supports chained stores which allow you to achieve similar results.

**Comment by dmitrypol** [comment]
Do you mean I can configure logster to write to different log files so `Rails.logger.foobar.info("message here") `will go to logs/foobar.log?  

I studied the code extensively and still not sure how to do that.  Could I you please provide an example?
