### ISSUE TITLE
Specify key namespace in Redis connection

### ISSUE THREAD

**Issue by dmitrypol** [discourse/logster#43]
It would be nice to specify a Redis key namespace.  Something like this:

```
  redis_connection = Redis.new(host: Rails.application.config.redis_host, port: 6379, db: 0, driver: :hiredis, namespace: 'logster')
  Logster.store = Logster::RedisStore.new(redis_connection)
```

**Comment by SamSaffron** [comment]
I support making a change to the redis store (not piggybacking the connection) to add support for namespacing the keys it uses

You can already do this today by using the redis namespace gem I think.

**Comment by n-rodriguez** [comment]
> You can already do this today by using the redis namespace gem I think.

Yes

**Comment by n-rodriguez** [comment]
😄
