### ISSUE TITLE
Bug with X-Accel-Redirect

### ISSUE THREAD

**Issue by n-rodriguez** [discourse/logster#46]
When X-Accel-Redirect is set and configured, logster stop working : Rack doesn't find files to send (assets).

**Comment by n-rodriguez** [comment]
I guess this is the culprit : https://github.com/discourse/logster/blob/master/lib/logster/middleware/viewer.rb#L19

**Comment by n-rodriguez** [comment]
Well, how do you get around this? :)

**Comment by SamSaffron** [comment]
We have it configured at discourse as well and all is fine.

Maybe add a location in your nginx config that bypasses fancy stuff in /logs

**Comment by n-rodriguez** [comment]
> Maybe add a location in your nginx config that bypasses fancy stuff in /logs

Yep. That's what I've done. Thanks!
