### ISSUE TITLE
Cluster of servers serving the same application

### ISSUE THREAD

**Issue by bitsapien** [discourse/logster#47]
Can Logster fetch logs from a cluster of servers serving the same application ? If one of my application servers has redis-server running, how would I configure Logster to listen to or post to that particular redis-server?

**Comment by SamSaffron** [comment]
well you can define and chain Logster::BaseStore objects then you can report errors to multiple locations if you wish. You can configure logster to talk to whatever redis server as well. 
Per:

```
Logster.store = Logster::RedisStore.new(redis_connection)
```

**Comment by bitsapien** [comment]
Thanks @SamSaffron. Managed to set it up 👍
