### ISSUE TITLE
Multiple NoMethodErrors in Rails 5 with quiet assets

### ISSUE THREAD

**Issue by alassek** [discourse/logster#48]
Greetings! First of all, thank you for this awesome, quick-and-dirty log viewer. I was about to write one myself when I found it. I've already found it to be very useful.

Unfortunately, in the course of updating an app to Rails 5 I've run into an issue. When `config.assets.quiet = true` is set, I am seeing multiple `NoMethodError`s causing my assets to fail in development.

I have created an example app at [https://github.com/alassek/logster-example](https://github.com/alassek/logster-example).

I was able to work around the first error with `Logster::Logger.include LoggerSilence`, but that leads to a different error involving `local_level=`.

**Comment by tgxworld** [comment]
To me, the bug is actually with Rails 5 which I've submitted a patch for.

https://github.com/rails/rails/pull/26874/files

**Comment by n-rodriguez** [comment]
Fixed in Rails 5.0.1
