### ISSUE TITLE
 stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by sahilchopra** [discourse/logster#50]
Logs:

/home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:12:in `block (2 levels) in broadcast': stack level too deep (SystemStackError)
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in`block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in `block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in`block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in `block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in`block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in `block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in`block (2 levels) in broadcast'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/activesupport-4.2.6/lib/active_support/logger.rb:13:in `block (2 levels) in broadcast'
     ... 4384 levels...
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
    from /home/sahil/.rvm/gems/ruby-2.3.0@wms/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by SamSaffron** [comment]
Logs indeed :)

I am going to need a bit more details, like repro steps, your Gemfile, custom settings on your part

**Comment by sahilchopra** [comment]
Gem file
  ruby '2.3.0'

  ## RAILS FRAMEWORK
  gem 'rails', '4.2.6'

  group :assets do
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'therubyracer', platforms: :ruby
  end
  gem 'bower-rails', '~> 0.10.0'
  gem 'remotipart', '~> 1.2'

  ## Core Gems
  gem 'jbuilder', '~> 2.0'

  ## Database Gems
  gem 'mongoid', '5.1.1'
  gem 'bson_ext'
  gem 'redis'
  gem 'logster'



Application.rb
Logster.store = Logster::RedisStore.new("redis://localhost:6379/")

config/initializers/logster.rb
Rails.logger.extend(ActiveSupport::Logger.broadcast(Logster.logger))
